config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#home'
  resources :events do
    resources :responses, only: [:create, :update, :destroy]
    get 'responses' => 'responses#for_event'
  end

  get 'users/responses' => 'responses#for_user'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :responses, dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true
  validates :start_datetime, presence: true
  validates :end_datetime, presence: true
  validates :user_id, presence: true

  def in_past?
    (self.all_day ? self.end_datetime.end_of_day : self.end_datetime) < Time.now
  end
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  validates :response, presence: true 
  validates :user_id, presence: true
  validates :event_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :lockable, :timeoutable, :confirmable
  has_many :events, dependent: :destroy
  has_many :responses, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

	def index
		@events = Event.all
		respond_to do |format|
			format.json
		end
	end

  def show
    @event = Event.find(params[:id])
    @response = current_user.responses.find_by(event: @event.id) || current_user.responses.build
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = "Event Created"
      redirect_to @event
    else
      render 'new'
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "Event updated"
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    flash[:success] = "Event deleted"
    redirect_to root_url
  end
	
  private

    def event_params
      params.require(:event).permit(:title, :description, :all_day, :start_datetime, :end_datetime, :user)
    end

    def correct_user
      @event = current_user.events.find_by(id: params[:id])
      redirect_to root_url if @event.nil?
    end

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :authenticate_user!

  def for_user
    @upcoming_responses = current_user.responses.select{|r| r.event.end_datetime >= Time.now}
    @upcoming_responses.sort_by! {|r| r.event.start_datetime}
    @old_responses = current_user.responses.select{|r| r.event.end_datetime < Time.now}
    @old_responses.sort_by! {|r| r.event.end_datetime}.reverse!
  end

  def for_event
    @responses = Event.find(params[:event_id]).responses
    @responses_y = @responses.select{|r| r.response == 1}
    @responses_m = @responses.select{|r| r.response == 0}
    @responses_n = @responses.select{|r| r.response == -1}
  end

  def create
    @response = current_user.responses.build(response_params)
    @response.event_id = params[:event_id]
    if @response.save
      flash[:success] = "Response saved"
    else
      flash[:danger] = "Response failed"
    end
    redirect_to @response.event || request.referrer
  end

  def update
    @response = Response.find(params[:id])
    if @response.update_attributes(response_params)
      flash[:success] = "Response updated"
    else
      flash[:danger] = "Error updating response"
    end
    redirect_to @response.event
  end

  def destroy
    @response = Response.find(params[:id]).destroy
    flash[:success] = "Response removed"
    redirect_to @response.event
  end

  private

    def response_params
      params.require(:response).permit(:response, :user, :event)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
		base_title = "Members of Barleyment Shared Calendar"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger">
      #{messages}
    </div>
    HTML

    html.html_safe
  end

  def current_user?(user)
    user == current_user
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/events/_event.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <strong class="panel-title"><%= @event.title %></strong>
    <% if @event.all_day %>
      <span class="small">on <%= @event.start_datetime.to_date.to_formatted_s :custom_date %></span>
      <span class="small">to <%= @event.end_datetime.to_date.to_formatted_s :custom_date %></span>
      <span class="badge pull-right">All Day</span>
    <% else %>
      <span class="small">from <%= @event.start_datetime.to_formatted_s :custom_datetime %> to <%= @event.end_datetime.to_formatted_s :custom_datetime %></span>
    <% end %>
  </div>
  <div class="panel-body">
    <%= @event.description %>
  </div>
  <div class="panel-footer">
    <%= link_to "Return to calendar",  root_path, class: "btn btn-default" %>
    <% if current_user?(@event.user) %>
      <div class="pull-right">
        <%= link_to "Edit", edit_event_path(@event), class: "btn btn-default" %>
        <%= link_to "Delete", @event, method: :delete, class: "btn btn-danger"%>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= yield(:form_title) %></h3>
  </div>
  <div class="panel-body">
    <%= form_for(@event) do |f| %>
      <%= render 'shared/error_messages', object: @event %>

      <div class="form-group">
        <%= f.label :title %><br />
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :description %><br />
        <%= f.text_area :description, rows: 10, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :all_day do %>
          <%= f.check_box :all_day %> All day event
        <% end %>
      </div>

      <div class="form-group">
        <%= f.label :start_datetime %>
        <%= f.datetime_local_field :start_datetime, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :end_datetime %>
        <%= f.datetime_local_field :end_datetime, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.submit yield(:button_text), class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_response_panel.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Responses</h2>
  </div>
  <div class="panel-body">
    <%= render partial: "response_summary", locals: {event: @event} %>
    <% if !@event.in_past? %>
      <hr>
      <h4>Response</h4>
      <%= render 'shared/response_form' %>
    <% end %>
  </div>
</div>

app/views/events/_response_summary.html.erb
<% if event.responses.count > 0 %>
  <div class="btn-group">
    <% if event.responses.where(response: 1).count > 0 %>
      <%= link_to event_responses_path(event, anchor: "attending"), { type: "button", class: "btn btn-success" } do %>
        Attending <span class="badge"><%= event.responses.where(response: 1).count %></span>
      <% end %>
    <% end %>
    <% if event.responses.where(response: 0).count > 0 %>
      <%= link_to event_responses_path(event, anchor: "maybe"), { type: "button", class: "btn btn-warning" } do %>
        Maybe <span class="badge"><%= event.responses.where(response: 0).count %></span>
      <% end %>
    <% end %>
    <% if event.responses.where(response: -1).count > 0 %>
      <%= link_to event_responses_path(event, anchor: "not_attending"), { type: "button", class: "btn btn-danger" } do %>
        Not attending <span class="badge"><%= event.responses.where(response: -1).count %></span>
      <% end %>
    <% end %>
  </div>
<% else %>
  <span>No responses</span>
<% end %>

app/views/events/edit.html.erb
<% provide(:title, 'Edit Event') %>
<% provide(:form_title, 'Edit Event') %>
<% provide(:button_text, 'Save Changes') %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render 'form' %>
  </div>
</div>

app/views/events/new.html.erb
<% provide(:title, 'New Event') %>
<% provide(:form_title, 'New Event') %>
<% provide(:button_text, 'Create Event') %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<div class="row">
  <div class="col-md-8">
    <%= render @event %>
  </div>
  <div class="col-md-4">
    <%= render 'response_panel' %>
  </div>
</div>

app/views/layouts/_calendar.html.erb
<script type='text/javascript'>

	$(document).ready(function() {
		
		$('#calendar').fullCalendar({
			header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,agendaWeek,agendaDay'
			},
			defaultDate: '<%= Time.new.strftime("%Y-%m-%d") %>',
			defaultView: 'month',
			editable: false,
			events: '/events.json',
			height: 650
		});		
	});

</script>

<div id="calendar"></div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted"><span class="glyphicon glyphicon-warning-sign"></span> Currently in development by <%= link_to 'BrAwnyTime', "https://github.com/BrAwnyTime" %>.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
	    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
			<%= link_to image_tag("beericon.png", alt: "MoB Home", size: "20x20") + " Home", root_url, class: "navbar-brand" %>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
      <% if user_signed_in? %>
       	<ul class="nav navbar-nav">
          <li><%= link_to 'New Event', new_event_path %></li>
        </ul>
      <% end %>
      <!--<ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Products <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/">Complete List</a></li>
          </ul>
        </li>
      </ul>-->
			<ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-user"></span> <%= current_user.email %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Change Profile', edit_user_registration_path %></li>
            <li><%= link_to 'My Responses', users_responses_path %></li>
            <li class="divider"></li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <span class="glyphicon glyphicon-log-out"></span> Log Out
              <% end %>
            </li>
          </ul>
        </li>
        <% else %>
          <li>
            <%= link_to new_user_session_path do %>
              <span class="glyphicon glyphicon-log-in"></span> Sign In
            <% end %>
          </li>
        <% end %>
      </ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |message_type, message| %>
		<% if message_type != "timedout" %>
			<div class="alert alert-<%= message_type %> alert-dismissible"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= message %></div>
		<% end %>
	<% end %>
	
	<%= yield %>

</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/responses/_old_response.html.erb
<%= link_to old_response.event, class: "list-group-item" do %>
	<h4 class="list-group-item-heading">
		<%= old_response.event.title %>
		<% case old_response.response
			when 1 %><span class="label label-success pull-right">Attending</span>
			<% when 0 %><span class="label label-warning pull-right">Maybe</span>
			<% when -1 %><span class="label label-danger pull-right">Not attending</span>
		<% end %>
	</h4>
	<p class="list-group-item-text small">Ended <%= time_ago_in_words(old_response.event.end_datetime) %> ago</p>
<% end %>

app/views/responses/_response.html.erb
<%= link_to response.event, class: "list-group-item" do %>
	<h4 class="list-group-item-heading">
		<%= response.event.title %>
		<% case response.response
			when 1 %><span class="label label-success pull-right">Attending</span>
			<% when 0 %><span class="label label-warning pull-right">Maybe</span>
			<% when -1 %><span class="label label-danger pull-right">Not attending</span>
		<% end %>
	</h4>
	<p class="list-group-item-text small">Starts in <%= time_ago_in_words(response.event.start_datetime) %></p>
<% end %>

app/views/responses/for_event.html.erb
<div class="row">
	<% if @responses.count > 0 %>
		<% if @responses_y.count > 0 %>
			<div class="col-sm-4">
				<ul class="list-group">
					<h4 id="attending" class="list-group-item list-group-item-success">Attending</h4>
					<% @responses_y.each do |r| %>
						<li class="list-group-item"><%= r.user.email %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<% if @responses_m.count > 0 %>
			<div class="col-sm-4">
				<ul class="list-group">
					<h4 id="maybe" class="list-group-item list-group-item-warning">Maybe</h4>
					<% @responses_m.each do |r| %>
						<li class="list-group-item"><%= r.user.email %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<% if @responses_n.count > 0 %>
			<div class="col-sm-4">
				<ul class="list-group">
					<h4 id="not_attending" class="list-group-item list-group-item-danger">Not attending</h4>
					<% @responses_n.each do |r| %>
						<li class="list-group-item"><%= r.user.email %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
	<% else %>
		<h4>This event currently has no responses.</h4>
	<% end %>
</div>

app/views/responses/for_user.html.erb
<div class="row">
  <% if @upcoming_responses.count > 0 %>
  <div class="col-sm-6">
  	<h4>Upcoming Events</h4>
  	<div class="list-group">
    	<%= render partial: "response", collection: @upcoming_responses %>
  	</div>
  </div>
  <% end %>
  <% if @old_responses.count > 0 %>
	  <div class="col-sm-6">
	  	<h4>Past Events</h4>
	  	<div class="list-group">
	    	<%= render partial: "old_response", collection: @old_responses %>
	  	</div>
	  </div>  
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_response_form.html.erb
<%= form_for [@event, @response] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.select(:response, [["Attending", 1, {'data-content' => "<span class='label label-success'>I'm going</span>"}], ["Maybe", 0, {'data-content' => "<span class='label label-warning'>Maybe</span>"}], ["Hells no", -1, {'data-content' => "<span class='label label-danger'>Not attending</span>"}]], {prompt: "Select your response"}, {class: "selectpicker"}) %>
  </div> 
  <script>
    $( document ).ready(function() {
      $('.selectpicker').selectpicker();
    });
  </script>
  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <% if !@response.new_record? %>
      <%= link_to "Remove", event_response_path(event_id: @event.id, id:@response.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    <% end %>  
  </div>

<% end %>

app/views/static_pages/home.html.erb
<% provide :title, "Home" %>

<% if user_signed_in? %>
	<%= render 'layouts/calendar' %>
<% else %>
	<div class="jumbotron">
		<h1>Welcome to the Members of Barleyment shared calendar!</h1>
		<p>If you already have a log in, you can sign in <%= link_to 'here', new_user_session_path %>.</p>
		<p>Otherwise, <%= link_to "Sign-Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	</div>
<% end %>